[2022-11-08T00:17:39.523+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.choose_best_model manual__2022-11-08T00:17:35.508136+00:00 [queued]>
[2022-11-08T00:17:39.563+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.choose_best_model manual__2022-11-08T00:17:35.508136+00:00 [queued]>
[2022-11-08T00:17:39.565+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-08T00:17:39.567+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-08T00:17:39.595+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-08T00:17:39.622+0000] {taskinstance.py:1383} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2022-11-08 00:17:35.508136+00:00
[2022-11-08T00:17:39.637+0000] {standard_task_runner.py:55} INFO - Started process 3344 to run task
[2022-11-08T00:17:39.642+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'choose_best_model', 'manual__2022-11-08T00:17:35.508136+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpcfqr12g7']
[2022-11-08T00:17:39.650+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask choose_best_model
[2022-11-08T00:17:39.759+0000] {task_command.py:376} INFO - Running <TaskInstance: my_dag.choose_best_model manual__2022-11-08T00:17:35.508136+00:00 [running]> on host 786e58bb7830
[2022-11-08T00:17:39.864+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=choose_best_model
AIRFLOW_CTX_EXECUTION_DATE=2022-11-08T00:17:35.508136+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-08T00:17:35.508136+00:00
[2022-11-08T00:17:39.880+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 211, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_dag.py", line 16, in choose_best_model
    best_accuracy = max(accuracies)
ValueError: max() arg is an empty sequence
[2022-11-08T00:17:39.894+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=my_dag, task_id=choose_best_model, execution_date=20221108T001735, start_date=20221108T001739, end_date=20221108T001739
[2022-11-08T00:17:39.911+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10 for task choose_best_model (max() arg is an empty sequence; 3344)
[2022-11-08T00:17:39.944+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-08T00:17:39.999+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
